In [ ]:
#pwd     print working directory
#uname -r
#lsb_release -a
#lscpu
#ls -la
#cd (directory name)/
#mkdir (name)
#apt install nano
#touch hola.py
#nano hola.py
#python --version
#rm hola.py               remove

# git config --global user.email "abcd"
# git config --global user.name "aaaa"
# git clone https://token@github.com/username/repository.git

# git add hola.py
# git commit "un script de python"
# git push

In [ ]:
import numpy as np

1. Crea un arreglo de 10 cincos.

In [ ]:
#cincos = np.ones(10)*5
cincos = np.full(10,5)
print(cincos)

[5 5 5 5 5 5 5 5 5 5]


2. Crea un arreglo de enteros pares desde 10, inclusive, hasta 50, inclusive.

In [ ]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

3. Crea una matriz cuadrada de 4 por 4 de números enteros aleatorios.

In [ ]:
np.random.randint(0,101,size=(4,4))

array([[ 29,  44,  97, 100],
       [ 79,  20,   2,  48],
       [ 24,  93,   2,  54],
       [ 46,  70,   7,  70]])

4. Genera un arreglo de 10 números aleatorios entre 0 y 1 y calcula la suma de todos sus elementos.

In [ ]:
diez_rand = np.random.rand(10)
print(diez_rand)
print(diez_rand.sum())

[0.73253238 0.2947028  0.55960928 0.75582183 0.44706548 0.08096409
 0.70347481 0.90365699 0.17026206 0.4974903 ]
5.145580027555182


5. Genera un arreglo de 10 números aleatorios entre 0 y 1 y calcula su media.


In [ ]:
otros_diez = np.random.rand(10)
print(otros_diez)
print(otros_diez.mean())

[0.96141778 0.99333024 0.73550065 0.02002866 0.47907931 0.36519704
 0.6133761  0.88171612 0.40166122 0.8959063 ]
0.6347213430307755
